name: r5s测试编译

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  30 15 * * Mon

jobs:

  build:

    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
      - name: download Friendlywrt
        run: |
          mkdir friendlywrt21-rk3568
          cd friendlywrt21-rk3568
          git clone https://github.com/friendlyarm/repo --depth 1 tools
          tools/repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v21.02 \
                  -m rk3568.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          tools/repo sync -c  --no-clone-bundle
      - name: Compile firmware
        run: |
          cd friendlywrt21-rk3568
          ./build.sh nanopi_r5s.mk
      - name: Assemble Artifact
        id: assemble_artifact
        run: |
         find ./ -name *.img 
         find ./friendlywrt21/ -name *.img 
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.8.0
        with:
          name: OpenWRT-${{ env.latest_release }}
          allowUpdates: true
          tag: ${{ env.latest_release }}
          commit: master
          replacesArtifacts: true
          token: ${{ secrets.workflow_token }}
          artifacts: rom/*

