name: r2s自动编译test
on:
  push:
    branches: [ main ]
  schedule:
    - cron: 30 15 * * Mon

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Prepare artifact
        run: find / -maxdepth 2 -name "*.config.seed" 
