name: r5s自动编译

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  30 15 * * Mon

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils tree bzip2 gawk gettext git libncurses5-dev libz-dev patch python unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          df -h
      - name: Download FriendlyWrt
        run: |
          mkdir friendlywrt21-rk3568
          cd friendlywrt21-rk3568
          git clone https://github.com/friendlyarm/repo --depth 1 tools
          tools/repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v21.02 \
                  -m rk3568.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          tools/repo sync -c  --no-clone-bundle
      - name: Update feeds
        run: |
          cd friendlywrt21-rk3568/friendlywrt/
          echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          ./scripts/feeds update -a 
          ./scripts/feeds install -a 
          make defconfig
      - name: mods
        run: |
          cd friendlywrt-rk3568
          sed -i '/=m/d;/CONFIG_VERSION/d;/CONFIG_SDK/d;/CONFIG_BUILDBOT/d;/CONFIG_ALL_KMODS/d;/CONFIG_ALL_NONSHARED/d;/CONFIG_DISPLAY_SUPPORT/d;/CONFIG_AUDIO_SUPPORT/d;/CONFIG_MAKE_TOOLCHAIN/d;/CGROUPS/d;/CONFIG_PACKAGE_luci-lib/d;/LLVM/d;/vsftpd=/d;/docker/Id;' `find configs/ -type f` scripts/mk-friendlywrt.sh
          cat $GITHUB_WORKSPACE/r5s.config.seed  | sed '/CONFIG_PACKAGE_kmod/d' > configs/rockchip/05-others
          echo 'CONFIG_TARGET_ROOTFS_PARTSIZE=800' >> configs/rockchip/05-others
          echo 'CONFIG_PACKAGE_mtd=y' >> configs/rockchip/05-others
          sed -i '/find/d' scripts/mk-friendlywrt.sh
          sed -i 's/RAW_SIZE_MB=1000/RAW_SIZE_MB=2000/' scripts/sd-fuse/mk-sd-image.sh
          cd friendlywrt
          . $GITHUB_WORKSPACE/scripts/merge_packages.sh
      - name: compile
        run: |
          cd friendlywrt21-rk3568
          ./build.sh nanopi_r5s.mk || (cd friendlywrt && make V=sc)
          cd friendlywrt
          make target/imagebuilder/compile
      - name: Compile firmware
        run: |
          make -j$(($(nproc) + 1)) -s || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
